### ISSUE TITLE
Get 0 in last data

### ISSUE THREAD

**Issue by morfair** [roysbike/zabbix-freeradius#1]
I have installed this tempalte completely, I tested it at zabbix server with zabbix_get and get data, but in web interface in Monitoring - Last Data I see zeros (0) for freeradius template's data.

**Comment by roysbike** [comment]
Execute please in console
echo "Message-Authenticator = 0x00, FreeRADIUS-Statistics-Type = 2, Response-Packet-Type = Access-Accept" | radclient -x 127.0.0.1:18121 status "password"

Default password= adminsecret

**Comment by morfair** [comment]
@roysbike in client's console I get data. In client's zabbix_agentd -k ... I get data. In server's zabbix_get I get data. But in Monitoring - Last Data I get zeros.

https://pp.vk.me/c638721/v638721986/8a27/azsshc1OtVw.jpg (sorry for selection highlighting)

Zabbix 3.2.1

**Comment by roysbike** [comment]
You specify a password in the macro?(Если что, можно ра русском))
<img width="1038" alt="2016-11-01 17 19 21" src="https://cloud.githubusercontent.com/assets/2388223/19892718/667d04ce-a057-11e6-8861-624af4347118.png">

**Comment by morfair** [comment]
@roysbike хорошо =) да, макро тоже пробовал прописать, всё равно нули, хоть пока и пароль дефолтный.

**Comment by roysbike** [comment]
а через zabbix_get получаете данные?

**Comment by morfair** [comment]
@roysbike да, вообще чудеса..

**Comment by roysbike** [comment]
Тогда включите debug на zabbix-agent и  zabbix-server ,  посмотрите логи

**Comment by morfair** [comment]
Я изменил в шаблоне во всех элементах данных "Хранение значения" на "Как есть" и всё заработало.

**Comment by roysbike** [comment]
Спасибо, исправлю

**Comment by morfair** [comment]
@roysbike я извиняюсь, еще подумал, правильнее, как мне кажется, было бы хранить "Дельта (простое изменение)", только так графики норм получаются.

**Comment by roysbike** [comment]
Ну это просто будет счетчик. После рестарта процесса он сбросится .

**Comment by morfair** [comment]
@roysbike поэтому и нужно всё же хранить дельту, просто в моих масштабах запросов/сек было слишком часто, и был постоянно 0, пики были настолько редкие, что сглаживались

**Comment by roysbike** [comment]
Хорошо, я добавлю. У меня 30-50 запрос в сек

**Comment by morfair** [comment]
Попробуйте добавить график или комплексный экран в шаблон, и на малых значениях проблема проявится. Тут по-экспериментировать надо.
