### ISSUE TITLE
radius.auth User Parameter missing?

### ISSUE THREAD

**Issue by jjhunt** [roysbike/zabbix-freeradius#3]
I'm just looking at the template and noticed there is a data item with a key of radius.auth.  However, I don't see a UserParameter associated with that key.  Would it be possible to include that info?  Thanks.

**Comment by mnik247** [comment]
+1.
What UserParameter for radius.auth?
Thanks.

**Comment by maximumG** [comment]
+1 same problem here

**Comment by jjhunt** [comment]
We used:

> UserParameter=radius.auth,/usr/bin/radtest -t mschap <user_name>   <user_password> 127.0.0.1 0 <client_secret> | grep "Received Access-Accept" | wc -l

**Comment by maximumG** [comment]
Thanks for the info, simple and straigthfoward :+1:
