### ISSUE TITLE
Error read dictionary

### ISSUE THREAD

**Issue by vmarteg** [roysbike/zabbix-freeradius#4]
Hello. 

In zabbix in info i have a message

"Preprocessing failed for: radclient: dict_init: /etc/freeradius/dictionary[33]: Couldn't open dictionary "/etc/freeradius/d...
1. Failed: cannot calculate delta (speed per second) for value of type "string": cannot convert value to numeric type"

Graphics also clean.

**Comment by roysbike** [comment]
Maybe local problem .  Show me please  file  /etc/freeradius/dictionary

**Comment by vmarteg** [comment]
Sorry. Problem was fixed.
